# Generated by Django 3.0.3 on 2020-02-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('year', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True)),
                ('score', models.CharField(choices=[('1', '1分'), ('2', '2分'), ('3', '3分'), ('4', '4分'), ('5', '5分'), ('6', '6分'), ('7', '7分'), ('8', '8分'), ('9', '9分'), ('10', '10分')], max_length=50)),
                ('content', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
