# Generated by Django 3.0.3 on 2020-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imdb_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
