# Generated by Django 3.0.3 on 2020-02-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
