# Generated by Django 3.0.3 on 2020-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200225_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_in_comment',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
