# Generated by Django 3.0.3 on 2020-02-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_like_num_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_in_comment',
            name='like_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like_num',
        ),
    ]
