# Generated by Django 3.0.3 on 2020-02-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20200227_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
