# Generated by Django 3.0.3 on 2020-02-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_comment_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_status',
            name='like_status',
            field=models.CharField(choices=[('1', '赞'), ('2', '不赞')], default='不赞', max_length=50),
        ),
    ]
